//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.Sprint.Vote.Dal.Interfaces
{
    using System;
    using System.Collections.Generic;
    
    public partial class VotesForCandidate
    {
        public int Id { get; set; }
        public Nullable<int> IdVoteUsers { get; set; }
        public Nullable<int> IdCandidates { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual VoteUser VoteUser { get; set; }
    }
}
