//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.Sprint.Vote.Dal.Interfaces
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoteUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VoteUser()
        {
            this.VotesForCandidates = new HashSet<VotesForCandidate>();
            this.FriendVotes = new HashSet<FriendVote>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ComesFrom { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public Nullable<int> EmailVerified { get; set; }
        public string City { get; set; }
        public string PostCode { get; set; }
        public string Street { get; set; }
        public Nullable<long> IdLanguages { get; set; }
        public Nullable<int> IdOccupations { get; set; }
        public Nullable<int> IdGeographicRegions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VotesForCandidate> VotesForCandidates { get; set; }
        public virtual GeographicRegion GeographicRegion { get; set; }
        public virtual Language Language { get; set; }
        public virtual Occupation Occupation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FriendVote> FriendVotes { get; set; }
    }
}
